name: Build


on:
  pull_request:
jobs:
  build:
    runs-on: fast
    env:
      ARCH: amd64
    steps:
    - uses: actions/checkout@v4
    - run: |
        git fetch --prune --unshallow
        mkdir build
    - name: Create repo 🔧
      id: create_repo
      uses: itxaka/luet-github-action@master
      with:
        FINAL_REPO: ttl.sh
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        DOCKER_ENDPOINT: quay.io
        REPOSITORY_TYPE: docker
        createRepo: true
        pushCache: true
        revisionSHA: true
    - name: Summary info
      run: |
        run: |
          echo "Repo created at quay.io/kairos/packages:${{ steps.create_repo.outputs.LUET_PUSHED_REPO }}-repository.yaml" >> $GITHUB_STEP_SUMMARY